# Generated by Django 5.1.1 on 2025-06-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stock_delete_crud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
