# Generated by Django 5.1.1 on 2025-06-11 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='custom_item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
