# Generated by Django 5.1.1 on 2025-06-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_billing_custom_item_name_alter_billing_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='billing',
            name='customer_phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
