# Generated by Django 5.1.1 on 2025-06-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_billing_customer_name_billing_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='gst',
            field=models.FloatField(default=0),
        ),
    ]
