# Generated by Django 5.1.1 on 2025-06-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_billing_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='customer_name',
            field=models.CharField(blank=True, default='Guest', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
