# Generated by Django 5.1.1 on 2025-06-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='core.invoice'),
        ),
    ]
