# Generated by Django 5.1.1 on 2025-06-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_billing_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='invoice',
        ),
    ]
