# Generated by Django 5.1.1 on 2025-06-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customerinvoice_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.customerinvoice'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='custom_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='gst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
