# Generated by Django 5.1.1 on 2025-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_billing_invoice_alter_billing_custom_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='inv_no',
            field=models.CharField(default='TEMP', max_length=20),
        ),
    ]
