# Generated by Django 5.1.1 on 2025-06-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customerinvoice_inv_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='billing',
            name='warranty',
            field=models.CharField(default='No Warranty', help_text='Enter warranty period (e.g., 1 Year, 6 Months)', max_length=100),
        ),
    ]
